# Generated by Django 5.0.2 on 2024-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_doctorpatientfile_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('prognosis', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorpatientfile',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorpatientfile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='DoctorPatientFile',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
