# Generated by Django 5.0.3 on 2024-04-24 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientfile',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
