# Generated by Django 5.0.3 on 2024-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_doctorpatientfile_doctor_doctorpatientfile_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientfile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Electrocardiogram (ECG)'),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Echocardiogram'),
        ),
    ]
