# Generated by Django 5.0.3 on 2024-04-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='ca',
            field=models.FloatField(verbose_name='Number of Major Vessels (0-3) Colored by Fluoroscopy'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='chol',
            field=models.IntegerField(verbose_name='Total Serum Cholesterol (mg/dl)'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='cp',
            field=models.CharField(choices=[(1, 'Typical Angina'), (2, 'Atypical Angina'), (3, 'Non-Anginal Pain'), (4, 'Asymptomatic')], max_length=256, verbose_name='Chest Pain Type'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='restecg',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'Abnormal - ST-T wave'), (2, 'Abnormal - Left Ventricular Hypertrophy')], max_length=256, verbose_name='Resting Electrocardiographic Results'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='slope',
            field=models.CharField(choices=[(1, 'Upsloping'), (2, 'Flat'), (3, 'Downsloping')], max_length=256, verbose_name='Slope of the Peak Exercise ST Segment'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='thal',
            field=models.CharField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], max_length=256, verbose_name='Thalassemia'),
        ),
    ]
