# Generated by Django 5.0.3 on 2024-04-28 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_doctorpatientfile_chol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='cp',
            field=models.IntegerField(choices=[(1, 'Typical Angina'), (2, 'Atypical Angina'), (3, 'Non-Anginal Pain'), (4, 'Asymptomatic')], verbose_name='Chest Pain Type'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Abnormal - ST-T wave'), (2, 'Abnormal - Left Ventricular Hypertrophy')], verbose_name='Resting Electrocardiographic Results'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='slope',
            field=models.IntegerField(choices=[(1, 'Upsloping'), (2, 'Flat'), (3, 'Downsloping')], verbose_name='Slope of the Peak Exercise ST Segment'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='thal',
            field=models.IntegerField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], verbose_name='Thalassemia'),
        ),
    ]
